"""
16/09/2025
fun_facts.py contains a list of fun facts that will be randomly drawn in main when user quits
Current list was generated by GPT-4.1 with auto-completion 16/09/25.
- Rotting Deputy aka Nexanoth
"""

fun_facts = [
    "The first computer virus was created in 1983 and was called the 'Elk Cloner'. It was designed to infect Apple II computers via floppy disk",
    "The first 1GB hard drive, introduced by IBM in 1980, weighed over 500 pounds and cost $40,000",
    "The original name for Windows was 'Interface Manager'",
    "The first webcam was created at the University of Cambridge to monitor a coffee pot, allowing researchers to see if there was coffee available without leaving their desks",
    "The QWERTY keyboard layout was designed to slow down typing speed to prevent typewriter jams, but it has persisted in modern keyboards",
    "The first email was sent by Ray Tomlinson to himself in 1971. The content of the email was simply 'QWERTYUIOP'",
    "The first computer mouse, invented by Douglas Engelbart in 1964, was made of wood",
    "The term 'bug' to describe a software glitch originated when a real moth was found causing issues in an early computer",
    "The first domain name ever registered was Symbolics.com on March 15, 1985",
    "The original PlayStation was not intended to be a gaming console; it was a collaboration between Sony and Nintendo to create a CD-ROM add-on for the Super Nintendo Entertainment System (SNES)",
    "The first website is still online. It was created by Tim Berners-Lee in 1991 and can be visited at http://info.cern.ch",
    "The first computer to use a graphical user interface (GUI) was the Xerox Alto, developed in the 1970s",
    "The first computer game, 'Spacewar!', was created in 1962 by Steve Russell and his team at MIT",
    "The first smartphone, the IBM Simon, was released in 1994 and had a touchscreen, email capability, and could send faxes",
    "The first 3D printer was created in 1983 by Chuck Hull, who also co-founded 3D Systems, one of the leading 3D printing companies",
    "The first computer animation was created in 1961 by Edward Zajac, who used a computer to generate a simple animation of a rotating cube",
    "The first computer virus for MS-DOS was called 'Brain' and was created in 1986 by two Pakistani brothers, Basit and Amjad Farooq Alvi",
]
